Repository Finance-uss/Finance_Us_BE, pull requests merged in 2025-01, with the labels that each got.

#8 [#5] Feat : 카테고리별 통계 API 구현
  src/main/java/finance_us/finance_us/domain/statistics/controller/CategoryStatisticsController.java
  src/main/java/finance_us/finance_us/domain/statistics/dto/CategoryGoalStatisticsResponse.java
  src/main/java/finance_us/finance_us/domain/statistics/dto/CategoryStatisticsResponse.java
  src/main/java/finance_us/finance_us/domain/statistics/dto/GoalStatisticsResponse.java
  src/main/java/finance_us/finance_us/domain/statistics/entity/CategoryStatistics.java
  src/main/java/finance_us/finance_us/domain/statistics/entity/PeriodStatistics.java
  src/main/java/finance_us/finance_us/domain/statistics/entity/status/Type.java
  src/main/java/finance_us/finance_us/domain/statistics/repository/CategoryStatisticsRepository.java
  src/main/java/finance_us/finance_us/domain/statistics/service/CategoryStatisticsService.java
Labels: ✨ FEAT

#11 [#6] Feat : 가계부 API 구현
  build.gradle
  src/main/java/finance_us/finance_us/domain/account/controller/AccountController.java
  src/main/java/finance_us/finance_us/domain/account/converter/AccountConverter.java
  src/main/java/finance_us/finance_us/domain/account/dto/AccountRequest.java
  src/main/java/finance_us/finance_us/domain/account/dto/AccountResponse.java
  src/main/java/finance_us/finance_us/domain/account/entity/Account.java
  src/main/java/finance_us/finance_us/domain/account/entity/status/AccountType.java
  src/main/java/finance_us/finance_us/domain/account/repository/AccountRepository.java
  src/main/java/finance_us/finance_us/domain/account/service/AccountService.java
  src/main/java/finance_us/finance_us/domain/category/repository/SubAssetRepository.java
  src/main/java/finance_us/finance_us/domain/category/repository/SubCategoryRepository.java
  src/main/java/finance_us/finance_us/global/config/WebSecurityConfig.java
  src/main/java/finance_us/finance_us/security/JwtAuthenticationFilter.java
  src/main/java/finance_us/finance_us/security/TokenProvider.java
Labels: ✨ FEAT

#9 [#2] Feat 사용자 인증 기능
  build.gradle
  src/main/java/finance_us/finance_us/domain/user/controller/AuthController.java
  src/main/java/finance_us/finance_us/domain/user/converter/AuthConverter.java
  src/main/java/finance_us/finance_us/domain/user/dto/AuthRequestDTO.java
  src/main/java/finance_us/finance_us/domain/user/dto/AuthResponseDTO.java
  src/main/java/finance_us/finance_us/domain/user/entity/User.java
  src/main/java/finance_us/finance_us/domain/user/repository/UserRepository.java
  src/main/java/finance_us/finance_us/domain/user/service/AuthService.java
  src/main/java/finance_us/finance_us/global/code/status/ErrorStatus.java
  src/main/java/finance_us/finance_us/global/config/WebSecurityConfig.java
  src/main/java/finance_us/finance_us/security/JwtAuthenticationFilter.java
  src/main/java/finance_us/finance_us/security/TokenProvider.java
Labels: ✨ FEAT

#12 [#7] Feat 게시글 기능
  src/main/java/finance_us/finance_us/domain/post/controller/PostController.java
  src/main/java/finance_us/finance_us/domain/post/converter/PostConverter.java
  src/main/java/finance_us/finance_us/domain/post/dto/PostRequest.java
  src/main/java/finance_us/finance_us/domain/post/dto/PostResponse.java
  src/main/java/finance_us/finance_us/domain/post/entity/Post.java
  src/main/java/finance_us/finance_us/domain/post/entity/status/Category.java
  src/main/java/finance_us/finance_us/domain/post/entity/status/PostType.java
  src/main/java/finance_us/finance_us/domain/post/repository/PostRepository.java
  src/main/java/finance_us/finance_us/domain/post/service/PostService.java
Labels: ✨ FEAT

#16 Feat/#13 statistics period
  src/main/java/finance_us/finance_us/domain/account/repository/AccountRepository.java
  src/main/java/finance_us/finance_us/domain/statistics/controller/PeriodStatisticsController.java
  src/main/java/finance_us/finance_us/domain/statistics/dto/MonthDetailResponse.java
  src/main/java/finance_us/finance_us/domain/statistics/dto/PeriodStatisticsResponse.java
  src/main/java/finance_us/finance_us/domain/statistics/repository/PeriodStatisticsRepository.java
  src/main/java/finance_us/finance_us/domain/statistics/service/CategoryStatisticsService.java
  src/main/java/finance_us/finance_us/domain/statistics/service/PeriodStatisticsService.java
Labels: ✨ FEAT

#17 Feat/#10 사용자 계정 관리 기능
  src/main/java/finance_us/finance_us/domain/account/service/AccountService.java
  src/main/java/finance_us/finance_us/domain/user/controller/AuthController.java
  src/main/java/finance_us/finance_us/domain/user/controller/UserController.java
  src/main/java/finance_us/finance_us/domain/user/converter/AuthConverter.java
  src/main/java/finance_us/finance_us/domain/user/dto/AuthRequestDTO.java
  src/main/java/finance_us/finance_us/domain/user/dto/AuthResponseDTO.java
  src/main/java/finance_us/finance_us/domain/user/repository/UserRepository.java
  src/main/java/finance_us/finance_us/domain/user/service/AuthService.java
  src/main/java/finance_us/finance_us/domain/user/service/UserService.java
  src/main/java/finance_us/finance_us/global/code/status/ErrorStatus.java
  src/main/java/finance_us/finance_us/security/JwtAuthenticationFilter.java
Labels: ✨ FEAT

#20 Feat/#18 이메일 인증 기능
  src/main/java/finance_us/finance_us/domain/user/controller/AuthController.java
  src/main/java/finance_us/finance_us/domain/user/service/MailService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨ FEAT

#27 Feat/#26 가계부 달력 기능
  src/main/java/finance_us/finance_us/domain/account/controller/AccountController.java
  src/main/java/finance_us/finance_us/domain/account/controller/CalendarController.java
  src/main/java/finance_us/finance_us/domain/account/converter/CalendarConverter.java
  src/main/java/finance_us/finance_us/domain/account/dto/CalendarDetailResponse.java
  src/main/java/finance_us/finance_us/domain/account/dto/CalendarResponse.java
  src/main/java/finance_us/finance_us/domain/account/entity/Account.java
  src/main/java/finance_us/finance_us/domain/account/repository/AccountRepository.java
  src/main/java/finance_us/finance_us/domain/account/service/AccountService.java
  src/main/java/finance_us/finance_us/domain/account/service/CalendarService.java
Labels: ✨ FEAT

#29 [#19] Feat : 알림 API 구현
  src/main/java/finance_us/finance_us/domain/notifications/controller/NotificationController.java
  src/main/java/finance_us/finance_us/domain/notifications/dto/NotificationListResponse.java
  src/main/java/finance_us/finance_us/domain/notifications/dto/NotificationResponse.java
  src/main/java/finance_us/finance_us/domain/notifications/dto/UnreadNotificationsResponse.java
  src/main/java/finance_us/finance_us/domain/notifications/entity/Notification.java
  src/main/java/finance_us/finance_us/domain/notifications/entity/status/ResourceType.java
  src/main/java/finance_us/finance_us/domain/notifications/entity/status/Type.java
  src/main/java/finance_us/finance_us/domain/notifications/repository/NotificationRepository.java
  src/main/java/finance_us/finance_us/domain/notifications/service/NotificationService.java
  src/main/java/finance_us/finance_us/global/code/status/ErrorStatus.java
Labels: ✨ FEAT

#25 Feat/#14 댓글 기능
  src/main/java/finance_us/finance_us/domain/comment/controller/CommentController.java
  src/main/java/finance_us/finance_us/domain/comment/converter/CommentConverter.java
  src/main/java/finance_us/finance_us/domain/comment/dto/CommentRequest.java
  src/main/java/finance_us/finance_us/domain/comment/dto/CommentResponse.java
  src/main/java/finance_us/finance_us/domain/comment/entity/Comment.java
  src/main/java/finance_us/finance_us/domain/comment/repository/CommentRepository.java
  src/main/java/finance_us/finance_us/domain/comment/service/CommentService.java
  src/main/java/finance_us/finance_us/domain/post/dto/PostRequest.java
  src/main/java/finance_us/finance_us/domain/post/entity/Post.java
  src/main/java/finance_us/finance_us/domain/post/service/PostService.java
Labels: ✨ FEAT

#35 Feat/#34 가계부 레포트&&팔로우 조회 구현
  src/main/java/finance_us/finance_us/domain/account/controller/AccountController.java
  src/main/java/finance_us/finance_us/domain/account/dto/AccountFollowResponse.java
  src/main/java/finance_us/finance_us/domain/account/dto/AccountReportResponse.java
  src/main/java/finance_us/finance_us/domain/account/repository/AccountRepository.java
  src/main/java/finance_us/finance_us/domain/account/service/AccountService.java
  src/main/java/finance_us/finance_us/domain/category/repository/SubCategoryRepository.java
  src/main/java/finance_us/finance_us/domain/follows/repository/FollowRepository.java
Labels: ✨ FEAT, ♻️ REFACTOR

#38 Feat/#32 팔로우 API 구현
  src/main/java/finance_us/finance_us/domain/follows/controller/FollowController.java
  src/main/java/finance_us/finance_us/domain/follows/dto/FollowResponse.java
  src/main/java/finance_us/finance_us/domain/follows/dto/FollowResponseWithLastId.java
  src/main/java/finance_us/finance_us/domain/follows/repository/FollowRepository.java
  src/main/java/finance_us/finance_us/domain/follows/service/FollowService.java
  src/main/java/finance_us/finance_us/domain/notifications/entity/Notification.java
  src/main/java/finance_us/finance_us/domain/notifications/service/NotificationService.java
  src/main/java/finance_us/finance_us/global/code/status/ErrorStatus.java
Labels: ✨ FEAT, ♻️ REFACTOR

#41 Feat/#33 게시글 스크랩 기능
  src/main/java/finance_us/finance_us/domain/post/controller/PostScrapController.java
  src/main/java/finance_us/finance_us/domain/post/converter/PostScrapConverter.java
  src/main/java/finance_us/finance_us/domain/post/dto/PostScrapResponse.java
  src/main/java/finance_us/finance_us/domain/post/repository/PostScrapRepository.java
  src/main/java/finance_us/finance_us/domain/post/service/PostLikeService.java
  src/main/java/finance_us/finance_us/domain/post/service/PostScrapService.java
Labels: ✨ FEAT

#47 Feat/#45 검색 API 구현
  src/main/java/finance_us/finance_us/domain/post/repository/PostRepository.java
  src/main/java/finance_us/finance_us/domain/search/controller/SearchController.java
  src/main/java/finance_us/finance_us/domain/search/dto/PostResponse.java
  src/main/java/finance_us/finance_us/domain/search/dto/PostSearchResponse.java
  src/main/java/finance_us/finance_us/domain/search/dto/UserResponse.java
  src/main/java/finance_us/finance_us/domain/search/dto/UserSearchResponse.java
  src/main/java/finance_us/finance_us/domain/search/service/SearchService.java
  src/main/java/finance_us/finance_us/domain/user/repository/UserRepository.java
Labels: ✨ FEAT

#48 Refactor/#46 사용자 관련 기능 수정
  src/main/java/finance_us/finance_us/domain/user/controller/AuthController.java
  src/main/java/finance_us/finance_us/domain/user/controller/UserController.java
  src/main/java/finance_us/finance_us/domain/user/service/AuthService.java
  src/main/java/finance_us/finance_us/domain/user/service/UserService.java
  src/main/java/finance_us/finance_us/global/code/status/ErrorStatus.java
Labels: ✨ FEAT, ♻️ REFACTOR

#51 Refactor/#49 통계, 알림, 검색, 팔로우 사용자 인증 로직 추가
  src/main/java/finance_us/finance_us/domain/account/repository/AccountRepository.java
  src/main/java/finance_us/finance_us/domain/category/controller/CategoryController.java
  src/main/java/finance_us/finance_us/domain/follows/controller/FollowController.java
  src/main/java/finance_us/finance_us/domain/follows/service/FollowService.java
  src/main/java/finance_us/finance_us/domain/notifications/controller/NotificationController.java
  src/main/java/finance_us/finance_us/domain/notifications/repository/NotificationRepository.java
  src/main/java/finance_us/finance_us/domain/notifications/service/NotificationService.java
  src/main/java/finance_us/finance_us/domain/search/controller/SearchController.java
  src/main/java/finance_us/finance_us/domain/search/service/SearchService.java
  src/main/java/finance_us/finance_us/domain/statistics/controller/CategoryStatisticsController.java
  src/main/java/finance_us/finance_us/domain/statistics/controller/PeriodStatisticsController.java
  src/main/java/finance_us/finance_us/domain/statistics/repository/CategoryStatisticsRepository.java
  src/main/java/finance_us/finance_us/domain/statistics/repository/PeriodStatisticsRepository.java
  src/main/java/finance_us/finance_us/domain/statistics/service/CategoryStatisticsService.java
  src/main/java/finance_us/finance_us/domain/statistics/service/PeriodStatisticsService.java
Labels: 🐛 FIX, ♻️ REFACTOR
