Repository Finance-uss/Finance_Us_BE, pull requests merged in 2025-02, with the labels that each got.

#53 Refactor/#52 커뮤니티 사용자 인증 로직 추가
  src/main/java/finance_us/finance_us/domain/comment/controller/CommentController.java
  src/main/java/finance_us/finance_us/domain/comment/controller/CommentLikeController.java
  src/main/java/finance_us/finance_us/domain/comment/repository/CommentLikeRepository.java
  src/main/java/finance_us/finance_us/domain/comment/service/CommentLikeService.java
  src/main/java/finance_us/finance_us/domain/comment/service/CommentService.java
  src/main/java/finance_us/finance_us/domain/post/controller/PostController.java
  src/main/java/finance_us/finance_us/domain/post/controller/PostLikeController.java
  src/main/java/finance_us/finance_us/domain/post/controller/PostScrapController.java
  src/main/java/finance_us/finance_us/domain/post/repository/PostLikeRepository.java
  src/main/java/finance_us/finance_us/domain/post/service/PostLikeService.java
  src/main/java/finance_us/finance_us/domain/post/service/PostScrapService.java
  src/main/java/finance_us/finance_us/domain/post/service/PostService.java
Labels: ♻️ REFACTOR

#54 Feat/#42 게시글 댓글 갯수 및 목록 반환
  src/main/java/finance_us/finance_us/domain/comment/controller/CommentController.java
  src/main/java/finance_us/finance_us/domain/comment/converter/CommentConverter.java
  src/main/java/finance_us/finance_us/domain/comment/dto/CommentResponse.java
  src/main/java/finance_us/finance_us/domain/comment/repository/CommentRepository.java
  src/main/java/finance_us/finance_us/domain/comment/service/CommentService.java
Labels: ✨ FEAT

#61 Refactor/#60 가계부 인증 로직 수정
  src/main/java/finance_us/finance_us/domain/account/controller/AccountController.java
  src/main/java/finance_us/finance_us/domain/account/controller/CalendarController.java
  src/main/java/finance_us/finance_us/domain/account/service/AccountService.java
  src/main/java/finance_us/finance_us/domain/account/service/CalendarService.java
  src/main/java/finance_us/finance_us/domain/account/service/LikeService.java
Labels: ♻️ REFACTOR

#67 Feat/#43 사용자 이미지 관련 API 구현
  ..bfg-report/2025-02-09/17-20-33/cache-stats.txt
  ..bfg-report/2025-02-09/17-20-33/deleted-files.txt
  ..bfg-report/2025-02-09/17-20-33/object-id-map.old-new.txt
  ..bfg-report/2025-02-09/17-20-33/protected-dirt/1dc27873-HEAD.csv
  .gitignore
  bfg-1.15.0.jar
  build.gradle
  src/main/java/finance_us/finance_us/domain/account/controller/AccountController.java
  src/main/java/finance_us/finance_us/domain/account/dto/AccountResponse.java
  src/main/java/finance_us/finance_us/domain/account/service/AccountImageExtractService.java
  src/main/java/finance_us/finance_us/domain/account/service/AccountService.java
  src/main/java/finance_us/finance_us/domain/account/service/GoogleOcrService.java
  src/main/java/finance_us/finance_us/domain/user/controller/UserController.java
  src/main/java/finance_us/finance_us/domain/user/converter/AuthConverter.java
  src/main/java/finance_us/finance_us/domain/user/entity/User.java
  src/main/java/finance_us/finance_us/domain/user/service/UserService.java
  src/main/java/finance_us/finance_us/global/code/status/ErrorStatus.java
  src/main/java/finance_us/finance_us/global/config/WebSecurityConfig.java
  src/main/java/finance_us/finance_us/global/exception/ExceptionAdvice.java
  src/main/resources/application.yml
Labels: ✨ FEAT, ♻️ REFACTOR

#74 Refactor/#73 댓글 관련 기능 userId 외 다른 정보 불러오기
  src/main/java/finance_us/finance_us/domain/comment/controller/CommentController.java
  src/main/java/finance_us/finance_us/domain/comment/controller/CommentLikeController.java
  src/main/java/finance_us/finance_us/domain/comment/converter/CommentConverter.java
  src/main/java/finance_us/finance_us/domain/comment/dto/CommentResponse.java
  src/main/java/finance_us/finance_us/domain/comment/service/CommentLikeService.java
  src/main/java/finance_us/finance_us/domain/comment/service/CommentService.java
  src/main/java/finance_us/finance_us/domain/post/controller/PostLikeController.java
  src/main/java/finance_us/finance_us/domain/post/service/PostLikeService.java
  src/main/java/finance_us/finance_us/global/code/status/ErrorStatus.java
Labels: ♻️ REFACTOR

#66 Feat/#65 가계부 subName 수정
  src/main/java/finance_us/finance_us/domain/account/service/AccountService.java
  src/main/java/finance_us/finance_us/domain/category/repository/SubAssetRepository.java
  src/main/java/finance_us/finance_us/domain/category/repository/SubCategoryRepository.java
Labels: ✨ FEAT

#69 Feat/#59 통계 테이블 관리 로직 구현
  src/main/java/finance_us/finance_us/domain/account/service/AccountService.java
  src/main/java/finance_us/finance_us/domain/category/service/CategoryService.java
  src/main/java/finance_us/finance_us/domain/statistics/controller/CategoryStatisticsController.java
  src/main/java/finance_us/finance_us/domain/statistics/controller/PeriodStatisticsController.java
  src/main/java/finance_us/finance_us/domain/statistics/entity/CategoryStatistics.java
  src/main/java/finance_us/finance_us/domain/statistics/entity/PeriodStatistics.java
  src/main/java/finance_us/finance_us/domain/statistics/repository/CategoryStatisticsRepository.java
  src/main/java/finance_us/finance_us/domain/statistics/repository/PeriodStatisticsRepository.java
  src/main/java/finance_us/finance_us/domain/statistics/service/CategoryStatisticsService.java
  src/main/java/finance_us/finance_us/domain/statistics/service/PeriodStatisticsService.java
Labels: ✨ FEAT

#78 Feat/#77 비밀번호 확인 및 사용자 관련 코드 리팩토링
  ..bfg-report/2025-02-09/17-23-14/cache-stats.txt
  ..bfg-report/2025-02-09/17-23-14/deleted-files.txt
  ..bfg-report/2025-02-09/17-23-14/object-id-map.old-new.txt
  .gitignore
  src/main/java/finance_us/finance_us/domain/user/controller/AuthController.java
  src/main/java/finance_us/finance_us/domain/user/controller/UserController.java
  src/main/java/finance_us/finance_us/domain/user/converter/AuthConverter.java
  src/main/java/finance_us/finance_us/domain/user/service/UserService.java
  src/main/java/finance_us/finance_us/global/code/status/ErrorStatus.java
  src/main/java/finance_us/finance_us/global/config/WebSecurityConfig.java
  src/main/java/finance_us/finance_us/global/exception/ExceptionAdvice.java
  src/main/java/finance_us/finance_us/security/JwtAuthenticationFilter.java
  src/main/java/finance_us/finance_us/security/TokenProvider.java
Labels: ✨ FEAT, ♻️ REFACTOR

#82 Feat/#76 S3 적용, 가계부 필드 추가
  src/main/java/finance_us/finance_us/domain/account/controller/AccountController.java
  src/main/java/finance_us/finance_us/domain/account/converter/CalendarConverter.java
  src/main/java/finance_us/finance_us/domain/account/dto/AccountRequest.java
  src/main/java/finance_us/finance_us/domain/account/dto/CalendarDetailResponse.java
  src/main/java/finance_us/finance_us/domain/account/dto/ReportResponse.java
  src/main/java/finance_us/finance_us/domain/account/entity/Account.java
  src/main/java/finance_us/finance_us/domain/account/service/AccountService.java
  src/main/java/finance_us/finance_us/global/S3/controller/S3Controller.java
  src/main/java/finance_us/finance_us/global/S3/dto/S3Request.java
  src/main/java/finance_us/finance_us/global/S3/dto/S3Response.java
  src/main/java/finance_us/finance_us/global/S3/service/S3Service.java
Labels: ♻️ REFACTOR

#79 Refactor/#75 에러핸들러 추가
  src/main/java/finance_us/finance_us/domain/account/service/AccountService.java
  src/main/java/finance_us/finance_us/domain/account/service/LikeService.java
  src/main/java/finance_us/finance_us/global/code/status/ErrorStatus.java
Labels: ♻️ REFACTOR

#85 [#84] Refactor : 기간별 통계 조회 시작, 종료 년도 및 월 선택 로직 추가
  src/main/java/finance_us/finance_us/domain/statistics/controller/PeriodStatisticsController.java
  src/main/java/finance_us/finance_us/domain/statistics/dto/PeriodStatisticsResponse.java
  src/main/java/finance_us/finance_us/domain/statistics/repository/PeriodStatisticsRepository.java
  src/main/java/finance_us/finance_us/domain/statistics/service/PeriodStatisticsService.java
Labels: ♻️ REFACTOR

#88 [#87] Refactor : 팔로우 목록 조회 시 전달 정보에 프로필 이미지 추가
  src/main/java/finance_us/finance_us/domain/account/service/LikeService.java
  src/main/java/finance_us/finance_us/domain/comment/service/CommentLikeService.java
  src/main/java/finance_us/finance_us/domain/comment/service/CommentService.java
  src/main/java/finance_us/finance_us/domain/follows/controller/FollowController.java
  src/main/java/finance_us/finance_us/domain/follows/dto/FollowResponse.java
  src/main/java/finance_us/finance_us/domain/follows/service/FollowService.java
  src/main/java/finance_us/finance_us/domain/notifications/service/NotificationService.java
  src/main/java/finance_us/finance_us/domain/post/service/PostLikeService.java
  src/main/java/finance_us/finance_us/global/code/status/ErrorStatus.java
Labels: ♻️ REFACTOR

#90 [#70] Feat : 알림 테이블 데이터 관리 로직 구현
  src/main/java/finance_us/finance_us/domain/notifications/service/NotificationService.java
Labels: ✨ FEAT

#92 Feat/#83 커뮤니티 S3 적용, 게시글 필드 추가, 유저 프로필 사진 주석처리 해제
  src/main/java/finance_us/finance_us/domain/comment/controller/CommentController.java
  src/main/java/finance_us/finance_us/domain/comment/converter/CommentConverter.java
  src/main/java/finance_us/finance_us/domain/comment/dto/CommentResponse.java
  src/main/java/finance_us/finance_us/domain/post/dto/PostRequest.java
  src/main/java/finance_us/finance_us/domain/post/dto/PostResponse.java
  src/main/java/finance_us/finance_us/domain/post/entity/Post.java
  src/main/java/finance_us/finance_us/domain/post/service/PostService.java
Labels: ✨ FEAT

#95 Feat/#93 대댓글 기능 구현
  src/main/java/finance_us/finance_us/domain/comment/controller/CommentController.java
  src/main/java/finance_us/finance_us/domain/comment/converter/CommentConverter.java
  src/main/java/finance_us/finance_us/domain/comment/dto/CommentRequest.java
  src/main/java/finance_us/finance_us/domain/comment/dto/CommentResponse.java
  src/main/java/finance_us/finance_us/domain/comment/entity/Comment.java
  src/main/java/finance_us/finance_us/domain/comment/service/CommentService.java
Labels: ✨ FEAT

#99 Refactor/#98 가계부-팔로우 uri 수정
  src/main/java/finance_us/finance_us/domain/account/controller/AccountController.java
  src/main/java/finance_us/finance_us/domain/account/service/AccountService.java
Labels: ♻️ REFACTOR

#100 Feat/#80 : 사용자 인증 디스코드 연동 기능 구현
  src/main/java/finance_us/finance_us/domain/user/controller/AuthController.java
  src/main/java/finance_us/finance_us/domain/user/dto/AuthRequestDTO.java
  src/main/java/finance_us/finance_us/domain/user/service/AuthService.java
  src/main/java/finance_us/finance_us/domain/user/service/DiscordWebhookService.java
  src/main/java/finance_us/finance_us/global/code/status/ErrorStatus.java
  src/main/java/finance_us/finance_us/global/config/WebSecurityConfig.java
  src/main/resources/application.yml
Labels: ✨ FEAT, ♻️ REFACTOR

#96 Feat/#86 카테고리 전반적인 리펙토링
  src/main/java/finance_us/finance_us/domain/category/controller/CategoryController.java
  src/main/java/finance_us/finance_us/domain/category/dto/converter/AssetConverter.java
  src/main/java/finance_us/finance_us/domain/category/repository/MainCategoryRepository.java
  src/main/java/finance_us/finance_us/domain/category/repository/SubCategoryRepository.java
  src/main/java/finance_us/finance_us/domain/category/service/CategoryService.java
  src/main/java/finance_us/finance_us/domain/user/controller/AuthController.java
  src/main/java/finance_us/finance_us/domain/user/controller/UserController.java
  src/main/java/finance_us/finance_us/global/code/status/ErrorStatus.java
Labels: ♻️ REFACTOR

#105 [#104] 기간별 통계 컨트롤러 수정
  src/main/java/finance_us/finance_us/domain/statistics/controller/PeriodStatisticsController.java
Labels: ♻️ REFACTOR

#102 Refactor/#101 커뮤니티 전반적인 리팩토링
  src/main/java/finance_us/finance_us/domain/comment/dto/CommentResponse.java
  src/main/java/finance_us/finance_us/domain/comment/repository/CommentLikeRepository.java
  src/main/java/finance_us/finance_us/domain/comment/service/CommentLikeService.java
  src/main/java/finance_us/finance_us/domain/comment/service/CommentService.java
  src/main/java/finance_us/finance_us/domain/post/controller/PostController.java
  src/main/java/finance_us/finance_us/domain/post/dto/PostResponse.java
  src/main/java/finance_us/finance_us/domain/post/repository/PostRepository.java
  src/main/java/finance_us/finance_us/domain/post/service/PostService.java
Labels: ♻️ REFACTOR

#103 Feat/#70 알림 테이블에 데이터 관리 로직 추가
  src/main/java/finance_us/finance_us/domain/comment/service/CommentService.java
  src/main/java/finance_us/finance_us/domain/notifications/controller/NotificationController.java
  src/main/java/finance_us/finance_us/domain/notifications/dto/NotificationListResponse.java
  src/main/java/finance_us/finance_us/domain/notifications/dto/NotificationResponse.java
  src/main/java/finance_us/finance_us/domain/notifications/service/NotificationService.java
  src/main/java/finance_us/finance_us/domain/search/controller/SearchController.java
  src/main/java/finance_us/finance_us/global/code/status/ErrorStatus.java
Labels: ✨ FEAT, ♻️ REFACTOR

#106 Feat/#94 메인 카테고리 삭제 로직 구현
  src/main/java/finance_us/finance_us/domain/category/controller/CategoryController.java
  src/main/java/finance_us/finance_us/domain/category/service/CategoryService.java
  src/main/java/finance_us/finance_us/global/code/status/ErrorStatus.java
Labels: ✨ FEAT

#109 Refactor/#108 커뮤니티 API 요약 설명 작성
  src/main/java/finance_us/finance_us/domain/comment/controller/CommentController.java
  src/main/java/finance_us/finance_us/domain/comment/controller/CommentLikeController.java
  src/main/java/finance_us/finance_us/domain/post/controller/PostController.java
  src/main/java/finance_us/finance_us/domain/post/controller/PostLikeController.java
  src/main/java/finance_us/finance_us/domain/post/controller/PostScrapController.java
Labels: ♻️ REFACTOR

#111 Refactor/#110- 가계부 팔로우 수정 && 스웨거 주석
  src/main/java/finance_us/finance_us/domain/account/controller/AccountController.java
  src/main/java/finance_us/finance_us/domain/account/controller/CalendarController.java
  src/main/java/finance_us/finance_us/domain/account/dto/FollowResponse.java
  src/main/java/finance_us/finance_us/domain/account/entity/Account.java
  src/main/java/finance_us/finance_us/domain/account/service/AccountService.java
  src/main/java/finance_us/finance_us/global/S3/controller/S3Controller.java
Labels: ♻️ REFACTOR

#115 Refactor#114: 이메일 확인 응답 변경
  src/main/java/finance_us/finance_us/domain/user/controller/AuthController.java
  src/main/java/finance_us/finance_us/domain/user/controller/UserController.java
  src/main/java/finance_us/finance_us/domain/user/service/AuthService.java
  src/main/java/finance_us/finance_us/domain/user/service/UserService.java
Labels: ♻️ REFACTOR

#117 [#116] Refactor : 사용자 검색 시 반환 정보 수정
  src/main/java/finance_us/finance_us/domain/search/dto/UserResponse.java
  src/main/java/finance_us/finance_us/domain/search/service/SearchService.java
Labels: ♻️ REFACTOR

#119 [#118] Refactor : 에러처리 수정
  src/main/java/finance_us/finance_us/domain/account/service/CalendarService.java
Labels: ♻️ REFACTOR

#121 [#120] Fix : 팔로우 목록 조회 버그 수정
  src/main/java/finance_us/finance_us/domain/follows/repository/FollowRepository.java
  src/main/java/finance_us/finance_us/domain/follows/service/FollowService.java
Labels: 🐛 FIX

#127 [#126] 알림 조회 시 리소스 문제 해결
  src/main/java/finance_us/finance_us/domain/notifications/dto/NotificationListResponse.java
  src/main/java/finance_us/finance_us/domain/notifications/service/NotificationService.java
Labels: 🐛 FIX

#129 Refactor/#128 커뮤니티 전반적인 리팩토링2
  src/main/java/finance_us/finance_us/domain/post/dto/PostResponse.java
  src/main/java/finance_us/finance_us/domain/post/repository/PostLikeRepository.java
  src/main/java/finance_us/finance_us/domain/post/repository/PostScrapRepository.java
  src/main/java/finance_us/finance_us/domain/post/service/PostService.java
Labels: ♻️ REFACTOR

#136 Refactor/#135 회원 탈퇴 기능 및 사용자 디스코드 에러 수정
  src/main/java/finance_us/finance_us/domain/user/service/AuthService.java
  src/main/java/finance_us/finance_us/domain/user/service/DiscordWebhookService.java
  src/main/java/finance_us/finance_us/domain/user/service/UserService.java
  src/main/java/finance_us/finance_us/global/config/WebSecurityConfig.java
Labels: ♻️ REFACTOR
